version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  mint_coast:
    build:
      context: ./mint_coast          
    container_name: mint_coast
    restart: always
    depends_on:  
      - db
    volumes:
      - ./mint_coast:/code
      - static_volume:/code/static
    env_file:
      - .env
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:                                  
      - mint_coast                     


volumes:
  pg_data:
  static_volume:
