# Generated by Django 4.2.5 on 2023-09-29 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mesh', models.TextField()),
                ('price', models.CharField(max_length=200)),
                ('is_mview', models.BooleanField(default=False)),
                ('poligons', models.CharField(max_length=200)),
                ('tris', models.CharField(max_length=200)),
                ('animate', models.BooleanField(default=False)),
                ('is_textures', models.BooleanField(default=False)),
                ('is_pbr', models.BooleanField(default=False)),
                ('is_unwrapped', models.BooleanField(default=False)),
                ('is_low_poly', models.BooleanField(default=False)),
                ('loading_date', models.DateTimeField(auto_now=True)),
                ('is_scan', models.BooleanField(default=False)),
                ('is_print', models.BooleanField(default=False)),
                ('is_video', models.BooleanField(default=False)),
                ('video', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mint_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='MUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('reg_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_open', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mint_app.muser')),
            ],
        ),
        migrations.CreateModel(
            name='Texture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mint_app.mmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mint_app.mmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Mview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mint_app.mmodel')),
            ],
        ),
        migrations.AddField(
            model_name='mmodel',
            name='tag',
            field=models.ManyToManyField(to='mint_app.tag'),
        ),
        migrations.AddField(
            model_name='mmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mint_app.muser'),
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.ManyToManyField(to='mint_app.mmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.ManyToManyField(to='mint_app.mmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mint_app.muser')),
            ],
        ),
    ]
