# Generated by Django 4.2.5 on 2024-02-09 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название категории')),
                ('path', models.TextField(default='/', verbose_name='Путь')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Тикет')),
                ('answer', models.TextField(blank=True, default=None, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('reg', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тикет',
                'verbose_name_plural': 'Тикеты',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.FileField(blank=True, default=None, upload_to='./news/020924140234/', verbose_name='Файл изображения')),
                ('date', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('mesh', models.FileField(blank=True, default=None, upload_to='./models/020924140234/', verbose_name='Файл модели')),
                ('format', models.CharField(choices=[('obj', 'obj'), ('fbx', 'fbx'), ('max', 'max'), ('mo', 'mo'), ('stl', 'stl')], default=None, max_length=300, verbose_name='Формат файла')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Цена')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Скидка в %')),
                ('for_sale', models.BooleanField(default=False, verbose_name='Для продажи')),
                ('mview', models.FileField(blank=True, default=None, upload_to='./models/020924140234/')),
                ('polygons', models.CharField(blank=True, default=None, max_length=200, verbose_name='Количество полигонов')),
                ('tris', models.CharField(blank=True, default=None, max_length=200, verbose_name='Количество треугольников')),
                ('animate', models.BooleanField(default=False, verbose_name='Анимация')),
                ('textures', models.FileField(blank=True, default=None, upload_to='./models/020924140234/textures/', verbose_name='Архив с текстурами')),
                ('is_pbr', models.BooleanField(default=False, verbose_name='PBR')),
                ('is_unwrapped', models.BooleanField(default=False, verbose_name='Есть развёртка')),
                ('is_low_poly', models.BooleanField(default=False, verbose_name='Лоу-поли модель')),
                ('loading_date', models.DateTimeField(auto_now=True)),
                ('is_scan', models.BooleanField(default=False, verbose_name='Скан')),
                ('is_print', models.BooleanField(default=False, verbose_name='Для 3d печати')),
                ('video', models.FileField(blank=True, default=None, upload_to='./models/020924140234/', verbose_name='Файл с видео')),
                ('style', models.CharField(choices=[('Stylized', 'Stylized'), ('Realistic', 'Realistic'), ('Anime', 'Anime'), ('Cartoon', 'Cartoon')], default=None, max_length=300, verbose_name='Стиль')),
                ('created_with', models.CharField(blank=True, default=None, verbose_name='Создано с помощью')),
                ('rendered_with', models.CharField(blank=True, default=None, verbose_name='Программа для рендера')),
                ('photo00', models.FileField(blank=True, default=None, upload_to='./models/020924140234/img/', verbose_name='Фото 1')),
                ('photo01', models.FileField(blank=True, default=None, upload_to='./models/020924140234/img/', verbose_name='Фото 2')),
                ('photo02', models.FileField(blank=True, default=None, upload_to='./models/020924140234/img/', verbose_name='Фото 3')),
                ('photo03', models.FileField(blank=True, default=None, upload_to='./models/020924140234/img/', verbose_name='Фото 4')),
                ('photo04', models.FileField(blank=True, default=None, upload_to='./models/020924140234/img/', verbose_name='Фото 5')),
                ('photo05', models.FileField(blank=True, default=None, upload_to='./models/020924140234/img/', verbose_name='Фото 6')),
                ('description', models.TextField(blank=True, default=None, verbose_name='Описание')),
                ('is_hidden', models.BooleanField(blank=True, default=False, verbose_name='Скрытая модель')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mint_app.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(blank=True, to='mint_app.tag', verbose_name='Тэги')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Начало')),
                ('end_date', models.DateTimeField(verbose_name='Окончание')),
                ('reason', models.TextField(blank=True, default=None, null=True, verbose_name='Причина')),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('model', models.ManyToManyField(to='mint_app.mmodel', verbose_name='Модели')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
    ]
