# Generated by Django 4.2.5 on 2023-09-29 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mint_app', '0002_alter_category_options_category_path_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mmodel',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.AlterModelOptions(
            name='muser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RenameField(
            model_name='mmodel',
            old_name='poligons',
            new_name='polygons',
        ),
    ]
