# Generated by Django 4.2.5 on 2023-09-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint_app', '0003_alter_mmodel_options_alter_muser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmodel',
            name='video',
            field=models.TextField(default=None),
        ),
    ]
