# Generated by Django 4.2.5 on 2023-09-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint_app', '0004_alter_mmodel_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmodel',
            name='created_with',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='mmodel',
            name='rendered_with',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='mmodel',
            name='style',
            field=models.TextField(default=None),
        ),
    ]
