# Generated by Django 4.2.5 on 2023-09-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint_app', '0005_mmodel_created_with_mmodel_rendered_with_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmodel',
            name='created_with',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='rendered_with',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='style',
            field=models.TextField(default=''),
        ),
    ]
