# Generated by Django 4.2.5 on 2023-09-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint_app', '0009_remove_mmodel_tag_mmodel_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmodel',
            name='mesh',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='video',
            field=models.FileField(upload_to=''),
        ),
    ]
