# Generated by Django 4.2.5 on 2023-09-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint_app', '0011_alter_mmodel_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmodel',
            name='video',
            field=models.FileField(blank=True, default=None, upload_to=''),
        ),
    ]
