# Generated by Django 4.2.5 on 2023-09-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint_app', '0012_alter_mmodel_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmodel',
            name='photo00',
            field=models.FileField(blank=True, default=None, upload_to='./static/models/<django.db.models.fields.CharField>_<django.db.models.fields.related.ForeignKey>/img/'),
        ),
        migrations.AddField(
            model_name='mmodel',
            name='photo01',
            field=models.FileField(blank=True, default=None, upload_to='./static/models/<django.db.models.fields.CharField>_<django.db.models.fields.related.ForeignKey>/img/'),
        ),
        migrations.AddField(
            model_name='mmodel',
            name='photo02',
            field=models.FileField(blank=True, default=None, upload_to='./static/models/<django.db.models.fields.CharField>_<django.db.models.fields.related.ForeignKey>/img/'),
        ),
        migrations.AddField(
            model_name='mmodel',
            name='photo03',
            field=models.FileField(blank=True, default=None, upload_to='./static/models/<django.db.models.fields.CharField>_<django.db.models.fields.related.ForeignKey>/img/'),
        ),
        migrations.AddField(
            model_name='mmodel',
            name='photo04',
            field=models.FileField(blank=True, default=None, upload_to='./static/models/<django.db.models.fields.CharField>_<django.db.models.fields.related.ForeignKey>/img/'),
        ),
        migrations.AddField(
            model_name='mmodel',
            name='photo05',
            field=models.FileField(blank=True, default=None, upload_to='./static/models/<django.db.models.fields.CharField>_<django.db.models.fields.related.ForeignKey>/img/'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='video',
            field=models.FileField(blank=True, default=None, upload_to='./static/models/<django.db.models.fields.CharField>_<django.db.models.fields.related.ForeignKey>/'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
