# Generated by Django 4.2.5 on 2023-09-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint_app', '0013_mmodel_photo00_mmodel_photo01_mmodel_photo02_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmodel',
            name='photo00',
            field=models.FileField(default=None, upload_to='./static/models/<django.db.models.fields.CharField>_<django.db.models.fields.related.ForeignKey>/img/'),
        ),
    ]
