# Generated by Django 4.2.5 on 2023-09-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint_app', '0014_alter_mmodel_photo00'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texture',
            name='model',
        ),
        migrations.RemoveField(
            model_name='mmodel',
            name='is_mview',
        ),
        migrations.AddField(
            model_name='mmodel',
            name='mview',
            field=models.FileField(blank=True, default=None, upload_to='./static/models/<django.db.models.fields.CharField>_<django.db.models.fields.related.ForeignKey>/'),
        ),
        migrations.AddField(
            model_name='mmodel',
            name='textures',
            field=models.FileField(blank=True, default=None, upload_to='./static/models/<django.db.models.fields.CharField>_<django.db.models.fields.related.ForeignKey>/textures/'),
        ),
        migrations.DeleteModel(
            name='Mview',
        ),
        migrations.DeleteModel(
            name='Texture',
        ),
    ]
