# Generated by Django 4.2.5 on 2023-09-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint_app', '0015_remove_texture_model_remove_mmodel_is_mview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmodel',
            name='format',
            field=models.CharField(choices=[('obj', 'obj'), ('fbx', 'fbx'), ('max', 'max'), ('mp', 'mo'), ('stl', 'stl')], default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='mesh',
            field=models.FileField(upload_to='./static/models/<django.db.models.fields.CharField>_<django.db.models.fields.related.ForeignKey>/'),
        ),
        migrations.DeleteModel(
            name='Format',
        ),
    ]
