# Generated by Django 4.2.5 on 2023-10-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint_app', '0020_alter_mmodel_mesh_alter_mmodel_mview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmodel',
            name='created_with',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='description',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='mesh',
            field=models.FileField(upload_to='./static/models/100323095737/'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='mview',
            field=models.FileField(blank=True, default=None, upload_to='./static/models/100323095737/'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='photo00',
            field=models.FileField(upload_to='./static/models/100323095737/img/'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='photo01',
            field=models.FileField(blank=True, default=None, upload_to='./static/models/100323095737/img/'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='photo02',
            field=models.FileField(blank=True, default=None, upload_to='./static/models/100323095737/img/'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='photo03',
            field=models.FileField(blank=True, default=None, upload_to='./static/models/100323095737/img/'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='photo04',
            field=models.FileField(blank=True, default=None, upload_to='./static/models/100323095737/img/'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='photo05',
            field=models.FileField(blank=True, default=None, upload_to='./static/models/100323095737/img/'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='polygons',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='price',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='rendered_with',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='textures',
            field=models.FileField(blank=True, default=None, upload_to='./static/models/100323095737/textures/'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='tris',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='video',
            field=models.FileField(blank=True, default=None, upload_to='./static/models/100323095737/'),
        ),
    ]
