# Generated by Django 4.2.5 on 2023-10-03 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mint_app', '0030_alter_mmodel_mesh_alter_mmodel_mview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmodel',
            name='animate',
            field=models.BooleanField(default=False, verbose_name='Анимация'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mint_app.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='created_with',
            field=models.TextField(blank=True, default=None, verbose_name='Создано с помощью'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='description',
            field=models.TextField(blank=True, default=None, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='format',
            field=models.CharField(choices=[('obj', 'obj'), ('fbx', 'fbx'), ('max', 'max'), ('mo', 'mo'), ('stl', 'stl')], default=None, max_length=300, verbose_name='Формат файла'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='is_low_poly',
            field=models.BooleanField(default=False, verbose_name='Лоу-поли модель'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='is_pbr',
            field=models.BooleanField(default=False, verbose_name='PBR'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='is_print',
            field=models.BooleanField(default=False, verbose_name='Для 3d печати'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='is_scan',
            field=models.BooleanField(default=False, verbose_name='Скан'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='is_unwrapped',
            field=models.BooleanField(default=False, verbose_name='Есть развёртка'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='mesh',
            field=models.FileField(blank=True, default=None, upload_to='./static/models/100323122821/', verbose_name='Файл модели'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='mview',
            field=models.FileField(blank=True, default=None, upload_to='./static/models/100323122821/'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='photo00',
            field=models.FileField(blank=True, default=None, upload_to='./static/models/100323122821/img/', verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='photo01',
            field=models.FileField(blank=True, default=None, upload_to='./static/models/100323122821/img/', verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='photo02',
            field=models.FileField(blank=True, default=None, upload_to='./static/models/100323122821/img/', verbose_name='Фото 3'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='photo03',
            field=models.FileField(blank=True, default=None, upload_to='./static/models/100323122821/img/', verbose_name='Фото 4'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='photo04',
            field=models.FileField(blank=True, default=None, upload_to='./static/models/100323122821/img/', verbose_name='Фото 5'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='photo05',
            field=models.FileField(blank=True, default=None, upload_to='./static/models/100323122821/img/', verbose_name='Фото 6'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='polygons',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Количество полигонов'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='price',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='rendered_with',
            field=models.TextField(blank=True, default=None, verbose_name='Программа для рендера'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='style',
            field=models.CharField(choices=[('Stylized', 'Stylized'), ('Realistic', 'Realistic'), ('Anime', 'Anime'), ('Cartoon', 'Cartoon')], default=None, max_length=300, verbose_name='Стиль'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='tags',
            field=models.CharField(default=None, max_length=300, verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='textures',
            field=models.FileField(blank=True, default=None, upload_to='./static/models/100323122821/textures/', verbose_name='Архив с текстурами'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='tris',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Количество треугольников'),
        ),
        migrations.AlterField(
            model_name='mmodel',
            name='video',
            field=models.FileField(blank=True, default=None, upload_to='./static/models/100323122821/', verbose_name='Файл с видео'),
        ),
    ]
